.travis.yml
setup.py

Added new Travis arm64 graviton2 instances to CI/CD.

Add arm64 targets to CI/CD pipeline

---

README.md
include/EquivalenceChecker.hpp
jkq/qcec/bindings.cpp
src/EquivalenceChecker.cpp
test/test_general.cpp

This PR adds the opt-in functionality for verifying dynamic circuits via translating such circuits to static ones.

Dynamic Circuits

---

README.md
docs/source/index.rst

This PR adjusts the README as well as the documentation to properly reflect the move to TUM.

:memo: Update README and Documentation

---

include/checker/dd/DDAlternatingChecker.hpp
include/checker/dd/DDConstructionChecker.hpp
include/checker/dd/DDSimulationChecker.hpp
src/checker/dd/DDEquivalenceChecker.cpp
src/checker/dd/DDSimulationChecker.cpp

This PR fixes a small warning reported by LGTM.

🚨 fix LGTM warning

---

README.md
docs/source/CompilationFlowVerification.rst
docs/source/install/Users.rst

This is just a tiny documentation update that fixes some inconsistencies.

📝 Small documentation update

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/pull_request_template.md

This PR adds issue and pull request templates to QCEC.

🔧 Add Issue and PR templates

---

README.md
docs/source/EquivalenceChecking.rst
docs/source/Publications.rst
docs/source/refs.bib

This PR adds the latest JETCAS paper on equivalence checking with the ZX-Calculus to the documentation and the README.

Updated docs with the JETCAS Publication.

---

.github/workflows/cpp-linter.yml
test/legacy/test_general.cpp

🐛  Fix `cpp-linter`

---

.github/codeql-config.yml
.github/workflows/codeql-analysis.yml
mqt/qcec/bindings.cpp
setup.py

This PR updates the GitHub CodeQL configuration in anticipation of the deprecation of LGTM.
Most importantly, it adds further checks and a custom build step for C++ to also cover the Python bindings and the tests.

🔧 Update CodeQL configuration

---

.pre-commit-config.yaml
mqt/qcec/compilation_flow_profiles.py
setup.py
test/python/test_construction.py

This tiny PR adds a couple more flake8 plugins to the pre-commit config to ensure that "modern" Python concepts are used throughout the project. It, in turn, incorporates all suggestions brought up by the newly enabled checks.

🚨 Further flake8 checks

---

pyproject.toml

This PR adds Tom as an author to the Python package.

👥 add @pehamTom as author

---

docs/source/CompilationFlowVerification.ipynb

This tiny PR fixes an issue concerning the Grover circuit examples in the docs.

🐛📝 Fix Grover circuit example

---

.github/codecov.yml
.github/workflows/python-ci.yml
noxfile.py

This PR adds further testing infrastructure to the Python side of QCEC:
- it adds a test run with the oldest `qiskit-terra` version we claim to support (mainly in order to make sure it actually works)
- it adds a coverage collection run for a different Python version (mainly to make sure that code that depends on the Python version is appropriately covered)
- it separates testing runs (which are executed on all systems with various Python versions) from coverage runs (which are only executed on Ubuntu with a selected set of Python versions)
Overall this should slightly increase the coverage metrics of the project and provide more safety that the library works as intended.
An additional benefit of the split is that CI runs a lot faster now since Python tests are no longer executed in …

🐍⚡🔧 Improve Python Testing Configuration 

---

.pre-commit-config.yaml
docs/source/CompilationFlowVerification.ipynb
docs/source/ParameterizedCircuits.ipynb
docs/source/Quickstart.ipynb

This tiny PR adds the `jupyter` option to the `black` pre-commit hook so that Jupyter notebooks are properly formatted as well.

🎨 Black for Jupyter pre-commit check

---

.github/workflows/python-ci.yml

The `setup-nox` action (https://github.com/daisylb/setup-nox) isn't very well maintained. This PR drops it in favor of a simple `pipx install nox` and the corresponding Python setup.

🔥 Replace weakly maintained `setup-nox` action

---

include/checker/zx/ZXChecker.hpp
src/CMakeLists.txt
src/EquivalenceCheckingManager.cpp
src/checker/zx/ZXChecker.cpp
test/legacy/test_general.cpp
test/test_equality.cpp
test/test_gate_cost_application_scheme.cpp
test/test_simple_circuit_identities.cpp
test/test_symbolic.cpp
test/test_zx.cpp

This PR ensures that QCEC also works with the latest QFR version. The latest update (https://github.com/cda-tum/qfr/pull/244) caused some breaking changes which need to be accounted for here.
All of the changes are minor and should not have any performance impact.

🚑 Fixup for newest QFR version

---

.gitmodules
include/checker/dd/DDAlternatingChecker.hpp
include/checker/dd/DDConstructionChecker.hpp
include/checker/dd/DDEquivalenceChecker.hpp
include/checker/dd/DDPackageConfigs.hpp
include/checker/dd/DDSimulationChecker.hpp
include/checker/dd/TaskManager.hpp
include/checker/dd/applicationscheme/ApplicationScheme.hpp
include/checker/dd/applicationscheme/GateCostApplicationScheme.hpp
include/checker/dd/applicationscheme/LookaheadApplicationScheme.hpp
include/checker/dd/applicationscheme/OneToOneApplicationScheme.hpp
include/checker/dd/applicationscheme/ProportionalApplicationScheme.hpp
include/checker/dd/applicationscheme/SequentialApplicationScheme.hpp
src/checker/dd/DDEquivalenceChecker.cpp
src/checker/dd/DDSimulationChecker.cpp

This PR builds on https://github.com/cda-tum/dd_package/pull/127 as well as https://github.com/cda-tum/qfr/pull/247 and refactors the DD template code.
None of the changes actually affect the performance or functionality of the code, but drastically improve IDE support.

🚸 Better DD package templating

---

.pre-commit-config.yaml
docs/source/conf.py
docs/source/library/Configuration.rst
docs/source/library/EquivalenceCheckingManager.rst
docs/source/library/Verify.rst
docs/source/library/VerifyCompilation.rst
docs/source/library/configuration/Application.rst
docs/source/library/configuration/Execution.rst
docs/source/library/configuration/Functionality.rst
docs/source/library/configuration/Optimizations.rst
docs/source/library/configuration/Parameterized.rst
docs/source/library/configuration/Simulation.rst
mqt/qcec/bindings.cpp
mqt/qcec/configuration.py
mqt/qcec/parameterized.py
mqt/qcec/pyqcec.pyi
mqt/qcec/verify.py
mqt/qcec/verify_compilation_flow.py
pyproject.toml
test/python/test_construction.py
test/python/test_verify.py

Up until now, an `EquivalenceCheckingManager` in Python could be constructed either from a `Configuration` object or via keyword arguments. In the verification methods this was used in an exclusive fashion, i.e., if keyword arguments were present, the configuration object was ignored.
Not only is this kind of unintuitive, but this duality introduced lots of code in the bindings and all the different verification functions that had to distinguish between arguments provided in form of a configuration object or keyword arguments.
With this PR, this is no longer the case. `Configuration` objects are the only way to construct an `EquivalenceCheckingManager` now. To keep the interface of all the outfacing verification functions the same, a method is provided that parses keyword arguments into a …

🚸♻️ Streamline C++-Python Interface for `EquivalenceCheckingManager`

---

docs/source/CompilationFlowVerification.ipynb
docs/source/library/VerifyCompilation.rst
mqt/qcec/verify_compilation_flow.py
test/python/test_verify_compilation.py

🚸 Warning for missing measurements

---

docs/source/_static/custom.css

This tiny PR improves dark-mode support in the docs a bit by making properties easier to read.
Thanks to @hillmich!

🎨 Small dark-mode docs improvement

---

.github/release-drafter.yml
setup.py

Some fine tuning for the release drafter action.
Also resolves a recent mypy warning due to a type ignore becoming obsolete.

🔧 Update Release Drafter Configuration

---

.cirrus.yml
.clang-tidy
include/Configuration.hpp
include/EquivalenceCheckingManager.hpp
include/checker/dd/DDConstructionChecker.hpp
include/checker/dd/applicationscheme/GateCostApplicationScheme.hpp
include/checker/dd/simulation/StateGenerator.hpp
mqt/qcec/bindings.cpp
src/checker/dd/DDAlternatingChecker.cpp
src/checker/dd/DDEquivalenceChecker.cpp
src/checker/dd/DDSimulationChecker.cpp
test/python/test_verify.py
test/test_equality.cpp
test/test_gate_cost_application_scheme.cpp
test/test_zx.cpp

This updates QCEC to use the latest MQT Core package. This includes several improvements in the underlying DD package.
Most notably, the limitation on 128 qubits is lifted and the DD package can now natively handle up to 65536 qubits.
> **Note**
> This just lifts the underlying technical limitation. Performance is not explicitly tuned for these large qubit numbers.

✨ Update MQT Core

---

.github/contributing.rst
.github/support.rst
LICENSE.md
README.md
docs/source/DevelopmentGuide.rst
docs/source/Installation.rst
docs/source/index.rst
pyproject.toml

This PR just fixes up a couple of things throughout the documentation regarding the move from `qcec` to `mqt-qcec` and from the `QFR` library to `MQT Core`.

📝 Prepare docs for new release

---

docs/source/conf.py
pyproject.toml
src/mqt/qcec/compilation_flow_profiles.py
test/python/test_compilation_flow_profiles.py
test/python/test_symbolic.py
test/python/test_verify_compilation.py

A couple of small updates and new rules for ruff

🚨 small ruff updates 

---

docs/source/CompilationFlowVerification.ipynb
docs/source/ParameterizedCircuits.ipynb
docs/source/Quickstart.ipynb

This small PR fixes a couple of warnings rendered in the docs due to a qiskit update.

📝 fix up docs warnings

---

docs/source/CompilationFlowVerification.ipynb
docs/source/_static/custom.css

This PR improves the dark-mode documentation by improving how strings are highlighted.

📝🎨 better dark mode docs

---

.pre-commit-config.yaml
pyproject.toml

This PR adds a new pre-commit check that runs Scientific Python's Repo Review and checks for the use of established best practices throughout the project.
Adding the check immediately revealed the use of a deprecated setting.

✨ add `sp-repo-review` to pre-commit checks

---

.github/codecov.yml
.github/workflows/cd.yml
.github/workflows/ci.yml
noxfile.py
src/python/bindings.cpp

This PR updates the reusable MQT workflows to their latest version. It also makes use of explicit versioning in order to avoid surprises caused by updates in the future and to allow getting updates from dependabot.

👷⬆️  update reusable workflows

---

.clang-tidy
.cmake-format.yaml
.editorconfig
.git_archival.txt
.gitignore
CMakeLists.txt
LICENSE.md
cmake/ExternalDependencies.cmake
cmake/cmake_uninstall.cmake.in
src/CMakeLists.txt
src/python/CMakeLists.txt

This PR updates a couple of the configuration files responsible for code formating, linting, etc.
This brings the project closer to the currently established best practises from mqt-core.

🎨 Code format and linting config update

---

pyproject.toml
src/mqt/qcec/_compat/__init__.py
src/mqt/qcec/_compat/importlib/__init__.py
src/mqt/qcec/_compat/importlib/resources.py
src/mqt/qcec/verify_compilation_flow.py
test/python/test_compilation_flow_profiles.py

This PR adds a compatibility module for easier managing of code related to `importlib.resources` inspired by scikit-build-core.
It also updates some of the mypy and ruff configuration.

🚸 introduce `importlib.resources` compatibility module

---

.pre-commit-config.yaml
docs/source/ParameterizedCircuits.ipynb
docs/source/PartialEquivalence.ipynb
pyproject.toml
src/checker/EquivalenceChecker.cpp
src/mqt/qcec/compilation_flow_profiles.py
test/python/test_symbolic.py
test/test_partial_equivalence.cpp

This PR adds schema validation to the pre-commit hooks. In addition, it also replaces codespell with `crates-ci/typos` and fix all newly brought up typos.
Finally, the PR runs `pre-commit autoupdate`.

⬆️🪝 update pre-commit config

---

.github/workflows/update-mqt-core.yml

This PR fixes the MQT Core update workflow. If successful, the corresponding CI run in this PR should trigger an update to MQT Core 2.6.0

🩹 fix MQT Core update workflow

---

.pre-commit-config.yaml
CMakeLists.txt
noxfile.py
src/CMakeLists.txt
src/python/bindings.cpp

This PR contains a couple of assorted library improvements including touch ups on the CMake config, the mypy configuration, and the pre-commit hooks.

🚸 Small library improvements

---

.github/renovate.json5
.github/workflows/release-drafter.yml
.pre-commit-config.yaml

Small tweaks to the renovate configuration to slighlty reduce the frequency of updates and enabling automerge for patch version updates.

🔧 update renovate configuration

---

docs/source/library/configuration/Execution.rst
noxfile.py

This small PR adds some documentation on how QCEC handles timeouts.
Resolves #477

📝 document timeout handling

---

.readthedocs.yaml

This pull request updates the documentation build process to Ubuntu 24.04 on ReadTheDocs.

👷📝 build RtD on Ubuntu 24.04

---

.github/release-drafter.yml
CHANGELOG.md
UPGRADING.md
docs/CHANGELOG.md
docs/UPGRADING.md
docs/conf.py
docs/index.md

This PR adds a changelog and upgrade guide infrastructure to MQT QCEC similar to the setup in MQT Core.

📝 add changelog and upgrade guide

---

CHANGELOG.md

Fixes a small copy&paste error in the changelog.

✏️ Fix typo in changelog

---

cmake/ExternalDependencies.cmake

This PR updates `googletest` to the latest available version.

⬆️ Update `googletest` from `v1.16.0` to `v1.17.0`

---

.readthedocs.yaml

This PR disables the PDF build on RtD because it keeps failing us. It is a copy of https://github.com/munich-quantum-toolkit/core/pull/1023.

📝🩹 Disable PDF build on RtD

---

.github/workflows/cd.yml
.pre-commit-config.yaml
.readthedocs.yaml
noxfile.py

This PR changes the test setup to not rebuild MQT Core from source. 
Fixes #661

🎨 Do not rebuild MQT Core in tests
