munich-quantum-toolkit/qcec

- .gitattributes
- .github/workflows/ci.yml
- CMakeLists.txt
- apps/sim_app.cpp
- include/EquivalenceChecker.hpp
- include/EquivalenceCheckingResults.hpp
- include/ImprovedDDEquivalenceChecker.hpp
- include/SimulationBasedEquivalenceChecker.hpp
- setup.py
- src/CompilationFlowEquivalenceChecker.cpp
- src/EquivalenceChecker.cpp
- src/ImprovedDDEquivalenceChecker.cpp
- src/SimulationBasedEquivalenceChecker.cpp
- test/test_general.cpp
This PR adapts the QCEC library to work with the new JKQ DD Package version released recently.
Performance of all decision diagram-based routines is expected to improve (especially those based on simulation).
✨ dynamic DD package size
✨ separate VectorDD and MatrixDD classes
⚡ improved garbage collection
⚡ improved memory allocation
⚡ improved hashing  
🔥 removed `line`
🔥 `validInstance` removed as such errors are now captured at the QFR level
⬆️ qfr
🔖 bump version
🐛 fix GitHub language statistic
💚 do not fail fast during CI
> Integrating the new DD Package version

- .github/codecov.yml
- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- CMakeLists.txt
- LICENSE
- MANIFEST.in
- README.md
- include/EquivalenceCheckingResults.hpp
- jkq/qcec/bindings.cpp
- setup.py
- test/test_general.cpp
A lot of (mostly minor) updates have happened since the last QCEC release. This PR incorporates the latest version of the QFR submodule and subsequently the underlying DD Package into QCEC. The most notable changes are:
- proper clearing of compute tables (iic-jku/dd_package#19)
- complex number formatting using polar coordinates and several improvements in complex table hashing (iic-jku/dd_package#20)
- several numerical stability updates for the underlying DD package (iic-jku/dd_package#21)
- updated Qiskit `QuantumCircuit` import (iic-jku/qfr#7)
- bugfixes for several optimization passes (iic-jku/qfr#9)
- possibility of cloning `QuantumComputation` objects and shortcuts for applying gates (iic-jku/qfr#11)
- fixes for `iSWAP` and `Peres` OpenQASM export (iic-jku/qfr#12)
- improved …
> Update to newest QFR version

- .github/workflows/deploy.yml
- CMakeLists.txt
- setup.py
This PR adds a bugfix regarding the realisation of RZ gates in our underlying package (see iic-jku/dd_package#25).
This fixes issues with verifying the equivalence of circuits compiled with Qiskit using the new IBM gate set `[ry, sx cx]`.
Furthermore, it adds `musllinux` wheels to the project.
Fixes #10
> Fix RZ gate bug

- .gitmodules
- README.md
- include/EquivalenceChecker.hpp
- include/ImprovedDDEquivalenceChecker.hpp
- jkq/qcec/bindings.cpp
- src/CompilationFlowEquivalenceChecker.cpp
- src/EquivalenceChecker.cpp
- src/ImprovedDDEquivalenceChecker.cpp
- test/test_general.cpp
This PR adds a new optimization pass (which is enabled by default) to the equivalence checker that establishes a canonical ordering of a circuit's gates.
This eliminates the unnecessary dependency of the checkers performance on the ordering of the gates in the circuit files.
In addition, this PR introduces an `identity_threshold` parameter for the `G->I<-G'` equivalence checker that allows to check whether the resulting decision diagram is close to the identity decision diagram up to the specified tolerance.\
This is important in cases of numerical inaccuracies, where the final decision diagram might be really close to the identity, but not exactly equal to it.
Last but not least, a small optimization is added to the `G->I<-G'` equivalence checker that tries to cancel identical gates …
> Gate Reordering and Approximate Comparison 

- .github/workflows/deploy.yml
- CMakeLists.txt
- pyproject.toml
- setup.py
This PR brings some minor improvements related to the CI/CD pipeline and Python packages:
- 🏗️ switch to PEP 517 `pyproject.toml`
- 🐛 🍎: deploying under macOS now produces fat binaries (i.e., for `x86_64` and `arm64` architectures). This allows to effectively build `universal2` wheels for Python 3.8 onwards and eventually makes the wheels work on M1-based Macs
- ⬆️ updated cibuildwheel to 2.3.0
- 🏗️ increase max CMake version to 3.22
- 🔖 increase version to 1.10.3
> Minor CI/CD Updates

- .github/workflows/deploy.yml
- CMakeLists.txt
- pyproject.toml
- setup.py
This PR reverts the default behaviour of building universal binaries and, in turn, universal wheels for macOS.
The main reason for this is that universal wheels are hard to create once external dependencies are involved (see, e.g., iic-jku/qmap#16) and it makes CI faster.
> 🍎 Revert to building separate instead of universal binaries and wheels

- include/checker/dd/simulation/StateGenerator.hpp
- src/EquivalenceCheckingManager.cpp
- test/test_equality.cpp
This PR eliminates a bug that prevented circuits with more than 63 qubits to be checked for equivalence with the default settings. To this end, classical stimuli with an arbitrary number of qubits can now be generated.
> ⚡ Loosen Requirements for Classical Stimuli Generation

- docs/source/install/Developers.rst
- jkq/__init__.py
- mqt/qcec/bindings.cpp
- pyproject.toml
- setup.py
This PR adopts a couple of very small bugfixes:
- the `verify` function was missing a default argument for the `configuration` parameter in the bindings
- a bug in the QFR library Qiskit `Layout` import prevented the import of circuits with a non-empty `_layout`but without an ancillary register
- the `tests` extra has been renamed to `test` which seems to be the more commonly used name
- a new `dev` extra has been added that installs all dependencies for development in one go.
> 🐛 Small bugfix update

- README.md
- docs/source/index.rst
- docs/source/install/Developers.rst
- docs/source/install/Users.rst
- docs/source/library/EquivalenceCheckingManager.rst
This PR updates parts of the documentation. Most importantly it adds information on how to build and run the C++ and Python tests and how to build the documentation locally.
Rather minor changes include the use of the dedicated `.. note::` role instead of manual disclaimers and the usage of footnotes to account for the JKQ/JKU/IIC legacy.
> 📝 Documentation update

- .gitignore
- .idea/cmake.xml
- .idea/runConfigurations/pip.xml
This PR adds `cmake` build configuration and `pip` run configuration profiles for the [CLion IDE](https://www.jetbrains.com/clion/) to the project.
The cmake build profiles (`Debug` and `Release`) automatically specify the `-DBUILD_QCEC_TESTS=ON` flag for building tests and the `-DBINDINGS=ON` flag for building Python bindings. This saves the hassle of finding out why the `qcec_test` or the `pyqcec` target is not available.
The `pip` run configuration can be used to automatically build the project in editable mode with development dependencies. This allows to easily build the project python package locally.
> 🚸🔧 Easy CLion configuration

- mqt/qcec/verify_compilation_flow.py
- setup.py
This PR adds `qiskit-terra` to the project dependencies of QCEC, which more clearly conveys our preferred way of using QCEC.
Furthermore, this should fix the documentation errors that were unfortunately not caught by the CI.
> 🔧🐍 Add `qiskit-terra` to project dependencies

- include/checker/zx/ZXChecker.hpp
- src/checker/zx/ZXChecker.cpp
This PR adds the means to allow for early termination in the ZX-based equivalence checker and eliminates waiting on a result when it is no longer needed.
To this end, the modular structure of the ZX Package is exploited and parts of the *simplification* code of the ZX Package is replicated in QCEC with additional termination checks.
This eventually allows to conveniently use the ZX checker per default without always waiting for it to finish.
> ✨ Early Termination of ZX Checker

- docs/source/conf.py
- setup.py
The `importlib` module is only available for `Python >=3.8` and has gained a lot more functionality since `3.10`.
This PR improves the Python version compatibility for building QCEC's documentation by introducing a fallback option for determining the package version.
Furthermore, it explicitly adds `pybtex` to the documentation requirements (`docs`).
> 🚸 Improve Python Compatibility of Documentation Building

- .github/codecov.yml
- .github/workflows/ci.yml
Until recently, the new codecov uploader did not provide the option to run `gcov` on its own (or at least the option was not well documented), which required us to generate that data manually. 
This PR removes this workaround, since the option is now available again.
This required some further configuration changes since codecov now also considers branch coverage by default which we, at least at the moment, don't care about too much.
> 🔧🔥 Remove Workaround for Coverage Computation

- MANIFEST.in
The recent addition of the ZX Package has increased the size of the source distribution for the QCEC package.
This PR reduces the size again by excluding unnecessary directories.
> ⚡📦 Leaner Source Distribution

- .github/workflows/ci.yml
- test/CMakeLists.txt
Our continuous integration tests are taking more and more time with every feature we add.
As off now, we always did a separate `build` step before conducting the actual `test` step. 
Furthermore, the `coverage` test depended on the success of all previous jobs.
This wasted quite some time, because various OSs take various amounts of time (Linux typically being the quickest).
As a consequence, this PR unifies the `build` and `test` steps and splits the previous build matrix into three separate runners (one for each OS). The coverage check then only depends on the success of the Linux run (as it also runs on Linux).
Finally, the parallel build level is increased to `3`, which only has an effect on macOS as off now.
> ⚡🔧 Faster CI

- include/checker/EquivalenceChecker.hpp
- include/checker/dd/DDConstructionChecker.hpp
- src/CMakeLists.txt
- src/checker/EquivalenceChecker.cpp
- src/checker/dd/DDConstructionChecker.cpp
According to https://llvm.org/docs/CodingStandards.html#provide-a-virtual-method-anchor-for-classes-in-headers:
> If a class is defined in a header file and has a vtable (either it has virtual methods or it derives from classes with virtual methods), it must always have at least one out-of-line virtual method in the class. Without this, the compiler will copy the vtable and RTTI into every .o file that #includes the header, bloating .o file sizes and increasing link times.
This PR fixes such cases for the QCEC library.
> ⚡ Avoid vtable Copy

- .github/codecov.yml
- mqt/qcec/bindings.cpp
- src/EquivalenceCheckingManager.cpp
The introduction of the ZX checker introduced a potential endless loop in the parallel equivalence check.
If it is detected that the ZX checker cannot be run on the given circuits an additional thread was spawned conducting a simulation run that was never signaled to be done and hence led to an endless loop.
Ci didn't show this until now since the error only happens for systems where `std::hardware_concurrency >= 18`.
This PR addresses this bug by introducing a sanity check before spawning simulations.
It also fixes some linter warnings that popped up along the way.
> 🐛 Fix Potential Endless Loop

- setup.py
CI is currently failing due to https://github.com/pypa/setuptools/pull/3488 implementing PEP660 editable installs in `setuptools` (starting with version `64`)
This PR works around that issue.
> 💚 Repair CI

- src/EquivalenceCheckingManager.cpp
- src/checker/zx/ZXChecker.cpp
- test/test_zx.cpp
This PR allows the ZXChecker to distinguish true equivalence and equivalence up to a global phase.
> Added handling of global phases

- mqt/qcec/bindings.cpp
As of now, the C++ bindings wrapped the circuit import and the creation of the `EquivalenceCheckingManager` in `try...catch` blocks and just printed the error message. This is rather undesirable and pybind11 explicitly provides the facilities to automatically translate C++ exceptions to corresponding Python exceptions.
This PR removes the `try...catch` blocks, thus, allowing to get better exception behavior in case of configuration errors or similar.
> 🚸 better Python bindings exceptions

- mqt/qcec/__init__.py
- mqt/qcec/bindings.cpp
- mqt/qcec/verify.py
- mqt/qcec/verify_compilation_flow.py
- test/python/test_verify.py
- test/python/test_verify_compilation.py
This PR slightly refactors and improves the usability of the `verify` functions in QCEC. More precisely:
- the `verify` function is refactored from a C++ binding function to a Python function in analogy to `verify_compilation_flow`
- keyword arguments can now be passed to `verify` functions as an alternative to a configuration object (makes it easier to just set single options)
> 🚸♻️ improved `verify` functions

- .github/dependabot.yml
This PR updates the dependabot configuration of the project.
For one, it adds proper timezones to the configuration.
Additionally, it removes the `ignore` config for GHA actions as recommended by https://github.com/scikit-hep/repo-review.
> 🔧 Update dependabot config

- MANIFEST.in
- mqt/qcec/verify_compilation_flow.py
- noxfile.py
- pyproject.toml
- setup.py
- test/python/test.py
This PR moves the metadata of the Python package from the `setup.py` file to the `pyproject.toml` file according to [PEP 621](https://peps.python.org/pep-0621/). `pyproject.toml` has been decided to be the future of Python packaging regarding metadata (and more). It also simplifies some of the code and makes it far more convenient to specify metadata and extras.
Unfortunately, this still does not allow to drop the `setup.py` file since there is no real alternative for building binary extensions at the moment. In the future we might look into https://github.com/scikit-build/scikit-build as a potential alternative.
This PR also brings along a couple of smaller fixes:
- `pyqcec` was accidentally created as a top-level module
- a recent update seems to have broken `pylint`. this is now fixed …
> 🐍🔧  Specify Metadata via PEP 621

- .github/workflows/cpp-linter.yml
This PR updates the cpp-linter to the latest major version (https://github.com/cpp-linter/cpp-linter-action/releases/tag/v2.0.0). This should speed up the runtime of the respective checks. Furthermore, by using the dedicated GitHub Action, we automatically benefit from dependabot updates in the future.
> ⚗️ Update cpp-linter to v2

- pyproject.toml
This PR loosens the dependency on `qiskit-terra` from `~=0.21.0` to `>=0.20,<0.22`. This ensures that QCEC can be installed alongside a wider range of Qiskit versions.
In principle, QCEC is compatible far further back down the history of `qiskit-terra`. However, Qiskit still regularly deprecates and changes interfaces. Maintaining compatibility with a large number of versions quickly becomes a burden. Hence `qiskit-terra~=0.19.0` is no longer officially supported.
> 📌 More leniency on the `qiskit-terra` version

- noxfile.py
- pyproject.toml
This PR updates the available nox sessions to also provide a `skip-install` option.
This speeds up repeated runs of the same command and, e.g., allows to work on the documentation more conveniently by once calling
```bash
nox -rs docs
```
and then, on repeated builds (if nothing has changed in the underlying Python package)
```bash
nox -rs docs -- skip-install
```
Furthermore, this PR simplifies the internal extra dependency logic of QMAP.
> 🔧 Update nox sessions

- include/Configuration.hpp
The following computation is currently being used to compute the maximum number of simulations to run:
https://github.com/cda-tum/qcec/blob/5ae4e6144d9144a128dbb21827960d2169d250ce/include/Configuration.hpp#L69-L70
However, `std::thread::hardware_concurrency` is not guaranteed to return a meaningful result. From its documentation:
> Number of concurrent threads supported. If the value is not well defined or not computable, returns ​`0​`.
In the above computation, if `std::thread::hardware_concurrency` happens to return `0` or reports only a single available thread, the subtraction would underflow. As a result, the maximum would be set to roughly `2**64` simulations -- essentially guaranteeing an endless run.
This PR adds an additional sanity check to make sure that the maximum number of …
> 🐛 Fix potential underflow bug in max simulation computation

- .github/codecov.yml
Per default, codecov reports the coverage status on a PR once the first report is uploaded. However, if there is more than one job tracking coverage (C++ and Python, for example), then this incorrectly reports a lowered coverage until both reports have been received.
Conveniently, codecov offers an option to delay the notification so that it only posts the notification after both reports have been received.
> 🔧 Codecov Config Update

- .github/workflows/ci.yml
- .github/workflows/python-ci.yml
Codecov has been really flaky over the past couple of months with uploads sporadically failing and runs showing up as failed on the Codecov website although passing on GitHub. This PR updates the codecov configuration of the project.
First of all, an upload token is used which should ensure that uploading succeeds in most cases.
Secondly, the action now fails whenever an error occurred in the process.
Lastly, the two coverage jobs are assigned flags which allows to separate the individual coverages a little more.
> 👷🔧 Update codecov config

- include/checker/dd/DDAlternatingChecker.hpp
- src/EquivalenceCheckingManager.cpp
- src/checker/dd/DDAlternatingChecker.cpp
- src/checker/dd/DDEquivalenceChecker.cpp
- test/test_equality.cpp
This PR ensures that the way ancillary and garbage qubits are treated in QCEC is theoretically sound and removes several corresponding "TODOs" in the code.
In particular, the alternating DD checker cannot be used whenever both circuits contain ancillary qubits that are acted upon.
Up until now, this did not cause any issues since, for the predominant use case of verifying compilation results, only one of the circuits typically uses ancillary qubits.
As a solution, the default verification scheme switches to the construction checker whenever it detects that the alternating checker is not capable of handling the circuits in question.
Furthermore, the alternating checker emits an exception should it ever be configured to still run on instances it can't handle.
Last, but not least, the matrix …
> 🚸 Ancillary and garbage handling

- .github/codecov.yml
Codecov now allows to explicitly split coverage metrics depending on certain flags being set.
The corresponding flags for the CI jobs where already introduced in #169.
This PR updates the configuration itself to use these flags and produce separate coverage checks for C++ and Python.
The envisioned benefit is that it becomes clearer, which part of the code base needs more tests.
> 🔧 Separate C++ and Python Coverage

- pyproject.toml
This PR makes QCEC compatible with the newest `qiskit-terra` release, which changed some internals of the `QuantumCircuit` class that broke the circuit import for compiled circuits in QCEC.
The cause for this issue was the change in https://github.com/Qiskit/qiskit-terra/pull/8802.
The (backwards-compatible) solution has been implemented in https://github.com/cda-tum/qfr/pull/207.
This PR also drops the upper-cap on the `qiskit-terra` version easing the integration with future versions of qiskit.
> 🚸 `qiskit-terra>=0.22.0` compatibility

- pyproject.toml
This small PR relaxes the (lower and upper) caps on QCEC's Python dependencies in order to increase it's compatibility with other libraries. This is mainly inspired by https://iscinumpy.dev/post/bound-version-constraints/.
In the future, it might make sense to introduce a CI check that ensures the lowest allowed versions still work. Such a job would be helpful for ensuring that QCEC continues to work with a large variety of external libraries and hardly depends on them. 
Pip `constraint` files could work for that purpose.
> 📌 More lenient package requirements

- .git_archival.txt
- .gitattributes
- pyproject.toml
Following https://scikit-hep.org/developer/packaging#versioning-mediumhigh-priority, this PR adds the necessary steps to allow git archives (including the ones generated from GitHub) to also support versioning. 
This requires `setuptools_scm>=7`.
> 📦 Support Versioning in Git Archives

- mqt/qcec/compilation_flow_profiles.py
Tests in the recent months have shown that the Qiskit transpiler is flaky when compiling single gates with optimization level O3. This leads to slightly different compilation flow profiles in QCEC and, as a consequence, sporadic failures in the test suite.
This PR adds a fixed seed to the respective `transpile` call in the hope of eliminating this flakiness.
> ❄️ Potential fix for flaky Python test

- .cirrus.yml
- .github/workflows/deploy.yml
- pyproject.toml
With this PR, Apple Silicon wheels are natively built on Cirrus CI and testing is enabled. In addition, Linux ARM wheels are built there.
Furthermore, Qiskit now ships Python 3.11 wheels; so testing wheels under that Python is no longer skipped.
🔥 This PR drops `musllinux` wheels since `qiskit` also doesn't provide corresponding wheels. As a result, Qiskit has to be built from source under these systems anyway.
Overall, this considerably simplifies the Python wheel setup.
Solves #149
> ✨ Cirrus CI

- .github/workflows/python-ci.yml
- noxfile.py
Qiskit now ships Python 3.11 wheels, so there is no reason left to not test under Python 3.11.
This PR adds the corresponding CI runs and modifies the existing ones.
> 🔧 add Python 3.11 tests

- .github/workflows/deploy.yml
- .github/workflows/emulated-wheels.yml
This PR adds CI support for building `s390x` and `ppc64le` Python wheels. This completes the long list of wheels that is offered by Qiskit. Hence, once this PR is merged and a release is created, QCEC provides binary wheels for any platform supported by Qiskit.
Since these are emulated platforms and GitHub places a 6h timeout on jobs, the jobs are split up as much as possible (creating 10 new jobs). Jobs for these platforms are split into a separate workflow file and only run on releases.
resolves #153
> 👷 Add CI workflows for `s390x` and `ppc64le` architectures

- src/checker/zx/ZXChecker.cpp
- test/test_zx.cpp
Fixes a bug where the ZX-checker simplifies a the equivalence checking miter to a diagram consisting only of wires. If this happens the checker erroneously didn't check whether the wires are hadamard wires.
Fixes #200
> Fix bug with hadamards in idenitity diagram.

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/cpp-linter.yml
- .github/workflows/deploy.yml
- .github/workflows/emulated-wheels.yml
- .github/workflows/python-ci.yml
This PR makes sure that CI jobs are not cancelled on the `main` branch, but only on pull requests.
This should avoid incomplete coverage data collection and ensure that every commit to the main branch passes CI.
> 🔧 Only cancel repeated CI jobs for Pull Requests

- .github/workflows/python-ci.yml
- .pre-commit-config.yaml
- README.md
- docs/source/Installation.rst
- noxfile.py
- pyproject.toml
Qiskit(-terra) is bound to drop Python 3.7 support in the upcoming `0.25.0` update and a warning is issued since the newly released `0.23.0`. 
To avoid any future disruptions, Python 3.7 support is dropped with this PR.
> 🐍🔥 Drop Python 3.7 support

- include/Configuration.hpp
- include/EquivalenceCheckingManager.hpp
- mqt/qcec/bindings.cpp
- mqt/qcec/parameterized.py
- mqt/qcec/pyqcec.pyi
- src/EquivalenceCheckingManager.cpp
- test/legacy/test_journal.cpp
- test/python/test_configuration.py
- test/python/test_symbolic.py
- test/python/test_verify.py
- test/test_symbolic.cpp
- test/test_zx.cpp
In the past, the way timeouts could be set was handled quite awkwardly by relying on `pybind`'s automatic conversion from `std::chrono::seconds` to some Python `datetime` object.
This PR simplifies the overall handling by changing the type of the `timeout` configuration parameter to a `double`.
Fixes #176
> ♻️ Simplify Timeout Handling

- src/checker/dd/DDAlternatingChecker.cpp
- test/python/test_verify.py
Fix an oversight in one of the compatibility checks for the alternating checker that could cause segfaults.
An exception was thrown erroneously if both circuits contained ancillary qubits that were idle.
While fixing, I took the opportunity to simplify the underlying code and eliminate some code duplication.
Fixes #236
> 🐛 Fix compatibility check in alternating checker

- include/EquivalenceCheckingManager.hpp
- src/EquivalenceCheckingManager.cpp
- test/legacy/test_journal.cpp
- test/test_zx.cpp
This PR reworks the logic on how conclusions on the final equivalence are drawn in both, the sequential and the parallel, equivalence checking flows. This also fixes a bug observed in #240 where the ZX checker (correctly) produced `no_information` on non-equivalent circuits, but instead of continuing with the rest of the flow, the computation was aborted.
This PR also introduces some additional logging/warning messages that (hopefully) clearly describe the behavior in some corner cases. I'd expect coverage to decrease for this PR, as those messages are not currently triggered in tests, but are more of a safety precaution.
Fixes #240
> 💡♻️ Improve corner-case logic for infering check result

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/cpp-linter.yml
- .github/workflows/deploy.yml
- .github/workflows/python-ci.yml
This tiny PR adds the `merge_group` label to the GitHub workflows in order to make them work with merge queues.
> 🔧 add `merge_group` to workflow configs

- .pre-commit-config.yaml
- pyproject.toml
This small PR updates the configuration of the ruff pre-commit hook. Since `v0.255`, the `target-version` configuration property can be inferred directly, which allows to simplify the configuration.
> ⬆️🪝 Update ruff and use automatic `target-version` inference

- .github/workflows/deploy.yml
https://github.com/pypa/gh-action-pypi-publish changed the naming convention for action parameters from snake_case to kebab-case. While the old syntax will be supported until the next major version increase, a warning is admitted as of the latest version.
This PR changes the `skip_existing` option to `skip-existing` to reflect the above change and silence the warning.
> 🩹 change PyPI upload option to kebab-case

- include/EquivalenceCheckingManager.hpp
- include/checker/dd/DDEquivalenceChecker.hpp
- include/checker/dd/DDSimulationChecker.hpp
- src/EquivalenceCheckingManager.cpp
- src/checker/dd/DDSimulationChecker.cpp
- test/python/test_verify.py
- test/test_equality.cpp
If an unhandled exception occurs in a C++ thread, `std::terminate` is called. This is undesirable, especially from the Python side, since there is no way for the exception to be propagated to Python and, thus, for handling it gracefully.
It just causes a crash of the Python executable.
Fortunately, C++ offers some ways to allow for exceptions from threads to be propagated to the main thread. 
This is done by using `std::async` instead of `std::thread`. Upon creation, it returns an `std::future` object that is used to refer to the return value of the asynchronous computation.
A future can hold the return value, but also an exception. Upon calling `future.get()`, either the value is returned or the stored exception is rethrown.
In this way, any exception happening concurrently is eventually …
> 🚸 Ensure exception propagation from threads via `std::async`

- pyproject.toml
An update in numpy has triggered a DeprecationWarning in Qiskit code that now trips up in our tests.
This PR ignores the respective warning as it does not concern us.
> 🩹 Ignore DeprecationWarning in Qiskit code

- .gitmodules
- CMakeLists.txt
- MANIFEST.in
- include/Configuration.hpp
- include/EquivalenceCheckingManager.hpp
- include/checker/zx/ZXChecker.hpp
- mqt/qcec/CMakeLists.txt
- mqt/qcec/bindings.cpp
- setup.py
- src/CMakeLists.txt
- src/EquivalenceCheckingManager.cpp
- src/checker/zx/ZXChecker.cpp
This PR replaces the QFR submodule with the newly introduced MQT Core library that subsumes the QFR, DD package, and ZX package. At the moment, this entails no functional changes and only required minor adaptions.
> 🚚 Move to MQT Core package

- pyproject.toml
Fixes CI. The newest Qiskit version introduced a new deprecation warning for some version attribute and, for some reason, that warning trips up pytest without our code actually using the deprecated attribute.
> 🩹 patch CI failure due to unconditional Qiskit deprecation warning

- include/checker/dd/applicationscheme/ProportionalApplicationScheme.hpp
- src/EquivalenceCheckingManager.cpp
- test/test_equality.cpp
This PR fixes a corner case where an empty circuit could lead to a division by zero error when trying to compute the gate ration between both circuits.
Furthermore, a shortcut is added for when both circuits are empty.
> 🐛 Fix a div-by-zero in `Proportional` strategy for empty circuit 

- pyproject.toml
- src/mqt/qcec/parameterized.py
The newest Qiskit release introduced some new deprecations and, unfortunately, also some internal deprecation warnings that now surface in our tests and must be ignored.
This PR adjusts MQT QCEC to these latest changes.
> adapt to new qiskit version.

- include/Configuration.hpp
- include/EquivalenceCheckingManager.hpp
- src/EquivalenceCheckingManager.cpp
- src/mqt/qcec/configuration.py
- src/mqt/qcec/pyqcec.pyi
- src/python/bindings.cpp
- test/CMakeLists.txt
- test/legacy/test_general.cpp
- test/python/test_dynamic_circuits.py
- test/test_dynamic_circuits.cpp
- test/test_simple_circuit_identities.cpp
This PR adds a new option to QCEC that allows to backpropagate the output permutation derived from the measurements of a circuit to the initial layout based on the optimization pass added in cda-tum/mqt-core#512.
This is especially helpful for verifying dynamic quantum circuits because it is rather hard (if not impossible) to define a proper initial layout for the circuit after it has been transformed to a regular quantum circuit by substituting resets and deferring measurements without an educated guess.
The new option is opt-in for now and can be activated by passing `backpropagate_output_permutation=True` as a keyword argument to the `verify` methods or by setting `config.optimizations.backpropagate_output_permutation=True` on a respective `Configuration` object.
Fixes #343
> ✨ Better dynamic circuit support

- include/checker/dd/DDEquivalenceChecker.hpp
- include/checker/dd/TaskManager.hpp
- include/checker/dd/applicationscheme/ApplicationScheme.hpp
- include/checker/dd/applicationscheme/GateCostApplicationScheme.hpp
- include/checker/dd/applicationscheme/LookaheadApplicationScheme.hpp
- include/checker/dd/applicationscheme/ProportionalApplicationScheme.hpp
- test/test_gate_cost_application_scheme.cpp
This was triggered by a clang-tidy warning that popped up in #348.
This PR also adjusts the `TaskManager` interface to take a reference to a package instance instead of a unique pointer; making the interface more generic.
This should unblock #348.
> 🚸🚨 Eliminate reference members and improve `TaskManager` interface

- pyproject.toml
- src/checker/dd/DDAlternatingChecker.cpp
- test/CMakeLists.txt
- test/test_partial_equivalence.cpp
This pull request updates MQT-QCEC such that it uses the updated version of `isCloseToIdentity()` of MQT-Core for Equivalence Checking in the Alternating Checker. As a consequence, the Alternating checker doesn't need to call `reduceGarbage()` anymore.
> ⚡ Eliminate garbage reduction in alternating checker

- .pre-commit-config.yaml
- CMakeLists.txt
- cmake/ExternalDependencies.cmake
- cmake/cmake_uninstall.cmake.in
- noxfile.py
- pyproject.toml
- src/CMakeLists.txt
- src/python/CMakeLists.txt
- test/CMakeLists.txt
This PR updates the mqt-core submodule and brings in some further advancements from #355.
Specifically, it switches to using `FetchContent` for obtaining `mqt-core`.
Per default, it is pointed to the vendored submodule via an overridable CMake variable.
> ⬆️ update mqt-core

- pyproject.toml
- test/python/constraints.txt
- test/python/test_construction.py
- test/python/test_symbolic.py
- test/python/test_verify.py
- test/python/test_verify_compilation.py
This PR works around some newly introduced deprecation warnings in the latest Qiskit version.
> 🚨 fix Qiskit 0.46.0 deprecation warnings

- pyproject.toml
- test/python/constraints.txt
This PR marks the official support of Qiskit 1.0 in QCEC.
In order to avoid all kinds of ugly compatibility hacks, this PR also changes the minimum required Qiskit version to 1.0.
Since Qiskit has devoted themselves to following semantic versioning from now on out, this hopefully means fewer compatibility changes in the future.
> ✨ Support for Qiskit 1.0

- test/test_symbolic.cpp
- test/test_zx.cpp
The new Apple Silicon runners from GitHub are just too fast for our timeout tests 🤯 
This PR reduces the timeouts in the ZX checker tests so that they should work even on significantly faster systems.
> 🩹 reduce timeouts for ZX timeout tests

- .clang-tidy
- include/checker/dd/DDConstructionChecker.hpp
- src/checker/dd/DDAlternatingChecker.cpp
- test/test_equality.cpp
- test/test_partial_equivalence.cpp
This PR pulls in the changes from cda-tum/mqt-core#358, which considerably changes the way matrix decision diagrams are represented. Particularly, any node resembling the identity is now eliminated and only implicitly represented.
This further compacts the representation of quantum gates and makes the identity the most compact it can be---a single terminal node.
The overall performance improvements are still to be evaluated. Surprisingly few changes were needed to make this work in QCEC.
> ✨ Stripping DDs of their identity

- .github/codecov.yml
- noxfile.py
- pyproject.toml
- test/python/constraints.txt
This PR updates the CI configuration to use uv by Astral (the creators of ruff), which is an extremely fast Python package installer and resolver, written in Rust. It is sesigned as a drop-in replacement for common pip and pip-tools workflows.
See https://github.com/astral-sh/uv
Similar to ruff, it is extremely fast and in very active development. This should speed up any of the Python-based CI runs without much confirguration overhead.
This PR refactors the `minimums` check to make use of `uv`'s `--resolution=lowest-direct" feature. This allows us to completely get rid of the `constraints.txt` file. 
Furthermore, it makes use of the new versions of `mqt-core`'s reusable workflows.
> :sparkles: Adopt `uv` in CI

- .github/workflows/cd.yml
- .github/workflows/ci.yml
This PR switches the reusable workflows from MQT Core to the ones hosted at https://github.com/cda-tum/mqt-workflows. This creates a better separation of concerns and allows for separate versioning of the workflows and the MQT Core library.
Furthermore, this PR adapts the configuration of the continuous deployment job so that the job is also triggered if the respective workflow file is updated. This should help to catch errors as early as possible when dependabot updates the workflow.
> 🧱 switch to dedicated reusable MQT workflows

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- pyproject.toml
- test/python/test_compilation_flow_profiles.py
This PR makes use of `cibuildwheel`'s latest addition of a `build[uv]` build frontend option that uses `uv` under the hood to speed up the build process.
Furthermore, it adjusts the Windows repair command to respect namespace packages.
Before: ~6h30m, After: ~5h50m
> ⚡🔧  Faster `cibuildwheel` and better Windows wheel repair

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- cmake/ExternalDependencies.cmake
- noxfile.py
- pyproject.toml
- src/python/bindings.cpp
The (ABI-stable) release candidate for Python 3.13 just released and the newest MQT Workflows include an updated version of cibuildwheel that supports building wheels for it.
This PR enables regular Python 3.13 builds and also enables builds for the new free-threaded variant.
> ✨ Python 3.13 Support

- .pre-commit-config.yaml
- docs/source/ParameterizedCircuits.ipynb
- docs/source/PartialEquivalence.ipynb
- noxfile.py
- pyproject.toml
- src/checker/EquivalenceChecker.cpp
- src/mqt/qcec/compilation_flow_profiles.py
- test/python/test_symbolic.py
- test/test_partial_equivalence.cpp
This PR updates the project to the latest scikit-build-core version that was just released and adapts the configuration correspondingly.
> ⬆️ update to scikit-build-core 0.10

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- pyproject.toml
This PR updates the MQT workflows to `v1.3`, which is the first version to offer moving minor tags that should reduce the update frequency.
Furthermore, the updated workflows combine the emulated wheel jobs to reduce overall build time and reduce the number of parallel jobs.
> ⬆️ update mqt-workflows to v1.3 (moving tag)

- pyproject.toml
- src/mqt/qcec/_compat/typing.py
- src/mqt/qcec/verify.py
- src/mqt/qcec/verify_compilation_flow.py
This PR removes the `typing_extensions` dependency for Python >= 3.11 and adds a compatibility typing module to abstract away the difference across Python versions.
> ➖ only require `typing_extensions` on Python < 3.11

- include/checker/dd/simulation/StateGenerator.hpp
- src/CMakeLists.txt
- src/checker/dd/simulation/StateGenerator.cpp
- src/python/CMakeLists.txt
- test/test_partial_equivalence.cpp
A follow-up to #444 that fixes a particular linking issue and furthermore improves the overall library link time dependencies by removing the template code from the `StateGenerator` and moving the code to the `.cpp` file.
> ♻️🩹 fix and improve MQT Core linking

- cmake/ExternalDependencies.cmake
- noxfile.py
- pyproject.toml
This small PR updates the requirement on pybind11 to `2.13.5` which contains a fix for some relative paths that could trip up compilers.
> ⬆️ require `pybind11 >= 2.13.5`

- .github/workflows/cd.yml
- pyproject.toml
CentOS 7, which the default `manylinux2014` image is based on, reached end-of-life in June 2024.
The only meaningful platforms left that do not provide a recent enough `glibc` version are some `Amazon Linux 2` platforms, which are not really relevant for the MQT.
This PR moves the Linux wheel builds to the more recent `manylinux_2_28` images, which offers many performance improvements and optimizations.
> 🐍⬆️ update image for Linux wheel builds to `manylinux_2_28`

- CMakeLists.txt
- README.md
- docs/source/Installation.rst
- noxfile.py
- pyproject.toml
Python 3.8 will reach end of live in October 2024.
Qiskit is already issuing deprecation warnings since a couple of releases when using it on Python 3.8.
This PR officially drops support for Python 3.8 in mqt-qcec.
> 🔥 drop Python 3.8 support

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- pyproject.toml
This PR updates the CD workflow so that anytime it runs on a push to `main`, it uploads the resulting package to Test PyPI. This allows to battle test the packages before official releases.
This will be especially important in the context of #432
> ⚗️ upload to Test PyPI for pushes on `main`

- .github/release-drafter.yml
- .github/renovate.json5
- .readthedocs.yaml
- noxfile.py
- pyproject.toml
This small PR contains a couple of small configuration updates. to the RtD configuration, the release drafter, as well as the scikit-build-core build directory config.
> 🔧 small project configuration updates

- cmake/ExternalDependencies.cmake
- test/test_simple_circuit_identities.cpp
Fixes #489.
The DCX gate (as well as the `xx_minus_yy` gate) had wrong gate matrix definitions in the underlying DD package within mqt-core.
These have now been fixed. A test has been added to check that the proper definition can be successfully verified.
> 🐛 Fix definition issue for DCX gate in DD package

- .github/workflows/ci.yml
- cmake/ExternalDependencies.cmake
- include/checker/dd/TaskManager.hpp
- src/checker/dd/DDAlternatingChecker.cpp
- src/checker/dd/DDSimulationChecker.cpp
- src/checker/dd/simulation/StateGenerator.cpp
This PR updates the MQT Core version used in QCEC to the latest version. This includes changes from cda-tum/mqt-core#674 and cda-tum/mqt-core#764.
SWAP eliding is now performed explicitly in QCEC instead of implicitly in the `getDD` method of MQT Core.
Furthermore, states generated by the DD package now have their ref count increased by default, which required subtle changes to the ref counting scheme.
> ⬆️👽  update to latest MQT Core version

- cmake/ExternalDependencies.cmake
- include/EquivalenceCheckingManager.hpp
- include/checker/dd/TaskManager.hpp
- src/checker/dd/simulation/StateGenerator.cpp
- test/test_dynamic_circuits.cpp
This PR updates the MQT Core version used in QCEC to the latest version. This includes changes from cda-tum/mqt-core#798.
Algorithms are now constructed slightly differently and some of the methods now take references instead of pointers.
This PR also fixes one compiler warning related to a potential uniniatialized usage in the equivalence checking manager.
> ⬆️👽 update to latest MQT Core version

- test/legacy/test_compilationflow.cpp
This pull request removes long-running test circuits from the unittests to improve the efficiency of the testing process. This change reduces execution time for test suites, ensuring quicker feedback during development.
> 🔥✅ remove long-running test circuits from unittests

- src/EquivalenceCheckingManager.cpp
This pull request introduces a dedicated name for ancillary registers introduced during preprocessing in QCEC, enhancing clarity and maintainability. Additionally, it optimizes logic by skipping ancillary and garbage setup when there is nothing to set up, improving efficiency.
> 🚸 Use dedicated name and optimize ancillary register setup

- pyproject.toml
This pull request fixes the coverage configuration to properly exclude the `literals.py` file from coverage reports. This ensures accurate reporting by excluding files that are not relevant to coverage metrics.
> 🩹 fix coverage configuration to properly exclude the `literals.py` file

- noxfile.py
- pyproject.toml
- uv.lock
This PR updates the minimum required scikit-build-core version to `0.11` to take advantage of its latest features.
First and foremost, it updates the pyproject metadata to use [PEP 639](https://peps.python.org/pep-0639/) license expressions.
This also resolved the Windows CI failures seen in #561 #562
Furthermore, it increases the verbosity of the nox test session logs, which should help debugging in the future.
> ⬆️🐍 update scikit-build-core to 0.11

- .github/workflows/upstream.yml
- noxfile.py
This pull request introduces a continuous testing workflow to ensure compatibility with the latest changes in the Qiskit main branch. This addition aims to maintain project stability and address potential integration issues promptly.
This is especially critical in light of the upcoming Qiskit 2.0 release.
The respective workflow will run once a week, on pull requests that change the respective file, as well as on manual workflow triggers.
> ✨Add continuous testing workflow for Qiskit main branch

- .readthedocs.yaml
This small PR fixes the RtD build pipeline.
The manylinux containers use a more recent version of gcc (gcc-14) than the default that comes with Ubuntu 24.04 (gcc-13).
Since `pybind11` hasn't had a new release with the looser compatibility between libraries compiled with different compilers or compiler versions, we need to build mqt-core from source for now in order to build the docs.
> 💚 fix RtD build

- CHANGELOG.md
- pyproject.toml
- src/mqt/qcec/compilation_flow_profiles.py
- src/mqt/qcec/verify_compilation_flow.py
- test/python/test_compilation_flow_profiles.py
- test/python/test_verify_compilation.py
This PR deprecates the `mode` argument of `generate_profile()` and the `ancilla_mode` argument of `verify_compilation`. This is in accordance with Qiskit's deprecation of the `mode` argument of `QuantumCircuit.mcx()` with version 2.1.
> 🗑️ Deprecate ancilla mode

- CHANGELOG.md
- UPGRADING.md
This PR prepares the release of v3.1.0.
> 🔖 Prepare release of v3.1.0

- noxfile.py
- test/python/test_compilation_flow_profiles.py
This PR ignores a deprecation warning for the Python 3.9 tests. This change will become unnecessary once we drop support for Python 3.9.
Fixes #672
> 🙈 Ignore Python 3.9 deprecation warning
